apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: statusquarkusio-h5cv
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-xajv-tenant/status-quarkus-io/statusquarkusio-h5cv@sha256:d5e1888a4c1214b431ec43bf94e464875f5e03d009ae89ca4c214cd5e9c98f3d
        name: my-java-quarkus
        resources: {}
status: {}
